### ISSUE TITLE
PHP to Java Script Online Conversion Site Down

### ISSUE THREAD

**Issue by elijah-z142** [tito10047/PHP-to-Javascript#24]
The website mentioned in the readme site is down at the moment (http://phptojs.mostka.com/). I have a PHP to Java converter at http://www.runtimeconverter.com, and will host your project for free at http://php2javascript.runtimeconverter.com/

Also, I just noticed that your repository does not mention any kind of a license. Please update with some kind of a usage license for others as well.

-elijah
[Runtime Converter (Online PHP to Java Converter](http://www.runtimeconverter.com)

**Comment by graciecorgi** [comment]
Just wanted to note that the online playground site is still down, just takes you to the nginx install successful page.

**Comment by elijah-z142** [comment]
No doubt it is not being maintained at all. You might try sending tito10047 an email (listed on https://github.com/tito10047), as he might have muted notifications from these issues.

In the meantime, I've left http://php2javascript.runtimeconverter.com/ running.

**Comment by tito10047** [comment]
link fixed. thanks @elijah-z142
