### ISSUE TITLE
Online converter doesn't convert crypt function

### ISSUE THREAD

**Issue by 3h6-1** [tito10047/PHP-to-Javascript#25]
When I put this in:
`$x=crypt("alpine", "/s");
echo $x`

It outputs:
`var x;
x = crypt("alpine", "/s");
console.log(x);`

But when I run that JavaScript I get:
`JavaScript error: Uncaught ReferenceError: crypt is not defined on line 3`

It didn't convert crypt.

**Comment by bagusindrayana** [comment]
i think crypt is php native function so dont avilabe in javascript
